service: student-api

provider:
    name: aws
    region: us-east-1
    runtime: provided.al2
    environment: 
        APP_ENV: prod
        APP_DEBUG: false
        DATABASE_URL: "mysql://studentstudi:12345678@db4free.net:3306/studentstudi?serverVersion=8.2.0&charset=utf8mb4"
        CORS_ALLOW_ORIGIN: '^https?://(localhost|127\.0\.0\.1)(:[0-9]+)?$'


plugins:
    - ./vendor/bref/bref

package:
    patterns:					          # Fichier exclus car non nécessaires pour
        - '!node_modules/**'		          # l'exécution de notre fonction
        - '!tests/**'    

functions:
    api:
        handler: public/index.php
        layers:
            - ${bref:layer.php-81}
        timeout: 28
        events:
            - httpApi:
                path: /
                method: ANY
            - httpApi:
                path: /api
                method: ANY
# ici je voudrais ajouter la router /api 

            # Ajoutez d'autres routes ici selon vos besoins